'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { collection, getDocs, query, where, orderBy } from 'firebase/firestore';
import { pdf, Document, Page, Text, View, StyleSheet } from '@react-pdf/renderer';
import { format } from 'date-fns';
import { AlertTriangle, Download, FileText } from 'lucide-react';
import { getClientDb } from '@/lib/firebase';
import { useAuth } from '@/lib/auth-context';
import type { Booking } from '@/types';
import Button from '@/components/ui/Button';
import Card from '@/components/ui/Card';
import BookingStatusBadge from '@/components/ui/BookingStatusBadge';
import RouteDisplay from '@/components/ui/RouteDisplay';
import { DetailPageSkeleton } from '@/components/ui/Skeleton';
import { useToast } from '@/components/toast/ToastProvider';

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: 'Helvetica' },
  title: { fontSize: 18, marginBottom: 8, fontWeight: 'bold' },
  subtitle: { fontSize: 12, marginBottom: 20, color: '#666' },
  section: { marginBottom: 16 },
  label: { fontWeight: 'bold', marginBottom: 4 },
  row: { marginBottom: 4 },
  footer: { marginTop: 30, fontSize: 9, color: '#888' },
  urgent: { color: '#DC2626', fontWeight: 'bold', marginBottom: 12 },
});

function EmergencyPdfDocument({
  booking,
  userName,
}: {
  booking: Booking;
  userName: string;
}) {
  const travelDate = booking.travelDate?.toDate?.();
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.urgent}>POLICE STOP — EMERGENCY DOCUMENT</Text>
        <Text style={styles.title}>CarryMate Item Declaration</Text>
        <Text style={styles.subtitle}>Generated {format(new Date(), 'dd MMM yyyy HH:mm')}</Text>

        <View style={styles.section}>
          <Text style={styles.label}>Booking reference</Text>
          <Text style={styles.row}>{booking.id}</Text>
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Carrier (traveller)</Text>
          <Text style={styles.row}>Document holder: {userName}</Text>
          <Text style={styles.row}>
            Route: {booking.fromCity} → {booking.toCity}
          </Text>
          {travelDate && (
            <Text style={styles.row}>Travel date: {format(travelDate, 'dd MMM yyyy')}</Text>
          )}
        </View>

        <View style={styles.section}>
          <Text style={styles.label}>Item details</Text>
          <Text style={styles.row}>Description: {booking.itemDescription}</Text>
          <Text style={styles.row}>Category: {booking.itemCategory.replace(/_/g, ' ')}</Text>
          <Text style={styles.row}>Weight: {booking.estimatedWeight} kg</Text>
          <Text style={styles.row}>Sender: {booking.senderName}</Text>
          <Text style={styles.row}>
            Recipient: {booking.recipientName} ({booking.recipientPhone})
          </Text>
          <Text style={styles.row}>Pickup: {booking.pickupLocation}</Text>
        </View>

        {booking.declarationData && (
          <View style={styles.section}>
            <Text style={styles.label}>Sender declaration</Text>
            <Text style={styles.row}>Signed by: {booking.declarationData.signedName}</Text>
            <Text style={styles.row}>Signed at: {booking.declarationData.signedAt}</Text>
            <Text style={styles.row}>
              Declared free of illegal drugs, weapons, cash, stolen goods, and dangerous items.
            </Text>
          </View>
        )}

        <View style={styles.section}>
          <Text style={styles.label}>Emergency contact</Text>
          <Text style={styles.row}>CarryMate Support: emergency@carrymate.com.au</Text>
          <Text style={styles.row}>Phone: +61 2 0000 0000</Text>
        </View>

        <Text style={styles.footer}>
          This document was generated by CarryMate for lawful community item delivery between
          Canberra, Sydney, and Melbourne. For verification contact support with the booking reference.
        </Text>
      </Page>
    </Document>
  );
}

export default function EmergencyPage() {
  const { user, userProfile, loading: authLoading } = useAuth();
  const router = useRouter();
  const { toast } = useToast();

  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState<string | null>(null);

  useEffect(() => {
    if (!authLoading && !user) {
      router.push('/login?redirect=/emergency');
    }
  }, [authLoading, user, router]);

  useEffect(() => {
    if (!user) return;

    async function load() {
      try {
        const [carryingSnap, sendingSnap] = await Promise.all([
          getDocs(
            query(
              collection(getClientDb(), 'bookings'),
              where('travellerId', '==', user!.uid),
              where('status', 'in', ['paid', 'picked_up']),
              orderBy('createdAt', 'desc')
            )
          ),
          getDocs(
            query(
              collection(getClientDb(), 'bookings'),
              where('senderId', '==', user!.uid),
              where('status', 'in', ['paid', 'picked_up']),
              orderBy('createdAt', 'desc')
            )
          ),
        ]);

        const all = [...carryingSnap.docs, ...sendingSnap.docs].map(
          (d) => ({ id: d.id, ...d.data() }) as Booking
        );
        const unique = Array.from(new Map(all.map((b) => [b.id, b])).values());
        setBookings(unique);
      } catch {
        setBookings([]);
      } finally {
        setLoading(false);
      }
    }

    void load();
  }, [user]);

  const generatePdf = async (booking: Booking) => {
    setGenerating(booking.id);
    try {
      const blob = await pdf(
        <EmergencyPdfDocument
          booking={booking}
          userName={userProfile?.displayName ?? 'CarryMate User'}
        />
      ).toBlob();

      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `carrymate-emergency-${booking.id.slice(0, 8)}.pdf`;
      link.click();
      URL.revokeObjectURL(url);
      toast('Emergency document downloaded.', 'success');
    } catch {
      toast('Failed to generate PDF.', 'error');
    } finally {
      setGenerating(null);
    }
  };

  if (authLoading || loading) return <DetailPageSkeleton />;

  return (
    <div className="mx-auto max-w-2xl">
      <div className="mb-8 flex items-start gap-3 rounded-lg border border-brand-danger/30 bg-red-50 p-4">
        <AlertTriangle className="mt-0.5 h-6 w-6 shrink-0 text-brand-danger" />
        <div>
          <h1 className="text-xl font-bold text-gray-900">Emergency document</h1>
          <p className="mt-1 text-sm text-gray-600">
            Generate a PDF declaration for police stops or inspections. Only available for active
            paid or in-transit bookings.
          </p>
        </div>
      </div>

      {bookings.length === 0 ? (
        <Card className="text-center">
          <FileText className="mx-auto mb-4 h-12 w-12 text-gray-300" />
          <p className="text-sm text-gray-500">
            No active bookings eligible for emergency documents.
          </p>
        </Card>
      ) : (
        <div className="space-y-4">
          {bookings.map((booking) => (
            <Card key={booking.id}>
              {booking.fromCity && booking.toCity && (
                <RouteDisplay
                  fromCity={booking.fromCity}
                  toCity={booking.toCity}
                  showDistance={false}
                  className="mb-3"
                />
              )}
              <div className="mb-4 flex items-center justify-between">
                <BookingStatusBadge status={booking.status} />
                <span className="text-xs text-gray-400">{booking.id.slice(0, 8)}…</span>
              </div>
              <p className="mb-4 text-sm text-gray-600 line-clamp-2">{booking.itemDescription}</p>
              <Button
                variant="danger"
                onClick={() => void generatePdf(booking)}
                loading={generating === booking.id}
              >
                <Download className="h-4 w-4" />
                Download emergency PDF
              </Button>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
