import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f9fafb' },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16, backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  headerTitle: { fontSize: 24, fontWeight: '700', color: '#111827' },
  notificationButton: { padding: 8, borderRadius: 8, backgroundColor: '#f3f4f6' },
  contentHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 12, backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e5e7eb' },
  filterIcon: { padding: 8, borderRadius: 8, backgroundColor: '#f3f4f6' },
  filterButtonText: { fontSize: 14, fontWeight: '600', color: '#6b7280' },
  deliveryList: { padding: 16 },
  deliveryCard: { backgroundColor: '#ffffff', borderRadius: 12, padding: 16, marginBottom: 12, shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4, elevation: 3 },
  deliveryHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 },
  deliveryTitleRow: { flexDirection: 'row', alignItems: 'center', flex: 1, gap: 8 },
  deliveryTitle: { fontSize: 16, fontWeight: '600', color: '#111827' },
  statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12 },
  statusText: { fontSize: 10, fontWeight: '700', color: '#ffffff' },
  deliveryRoute: { marginBottom: 12 },
  routePoint: { flexDirection: 'row', alignItems: 'center', marginVertical: 4 },
  routeDot: { width: 8, height: 8, borderRadius: 4, marginRight: 12 },
  pickupDot: { backgroundColor: '#059669' },
  dropoffDot: { backgroundColor: '#dc2626' },
  routeLine: { width: 2, height: 12, backgroundColor: '#d1d5db', marginLeft: 4, marginVertical: 2 },
  routeText: { fontSize: 14, color: '#374151', flex: 1 },
  deliveryDetails: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 12 },
  detailRow: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  detailText: { fontSize: 14, color: '#6b7280' },
  priceText: { fontSize: 16, fontWeight: '600', color: '#059669' },
  instructionsContainer: { backgroundColor: '#f9fafb', borderRadius: 8, padding: 12, marginBottom: 12 },
  instructionsLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 4 },
  instructionsText: { fontSize: 14, color: '#6b7280', lineHeight: 18 },
  itemsList: { marginBottom: 12 },
  itemsLabel: { fontSize: 14, fontWeight: '600', color: '#374151', marginBottom: 6 },
  itemText: { fontSize: 14, color: '#6b7280', marginBottom: 2 },
  acceptButton: { backgroundColor: '#2563eb', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 8, gap: 8 },
  acceptButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '600' },
  actionButtonsRow: { flexDirection: 'row', gap: 12 },
  trackButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 8, backgroundColor: '#eff6ff', gap: 6 },
  trackButtonText: { color: '#2563eb', fontSize: 12, fontWeight: '600', textAlign: 'center' },
  chatButton: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', paddingVertical: 12, borderRadius: 8, backgroundColor: '#ecfdf5', gap: 6 },
  chatButtonText: { color: '#059669', fontSize: 12, fontWeight: '600', textAlign: 'center' },
  userDetailsSection: { marginBottom: 12, paddingVertical: 8, borderTopWidth: 1, borderTopColor: '#f3f4f6' },
  userDetail: { flexDirection: 'row', alignItems: 'flex-start', marginBottom: 8, gap: 8 },
  userDetailContent: { flex: 1 },
  userDetailLabel: { fontSize: 12, color: '#6b7280', fontWeight: '500', marginBottom: 2 },
  userDetailName: { fontSize: 14, color: '#111827', fontWeight: '600', marginBottom: 4 },
  ratingContainer: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  ratingText: { fontSize: 12, color: '#374151', fontWeight: '500' },
  ratingCount: { fontSize: 11, color: '#9ca3af', fontWeight: '400' },
  emptyState: { alignItems: 'center', paddingVertical: 60 },
  emptyTitle: { fontSize: 20, fontWeight: '700', color: '#111827', marginBottom: 8 },
  emptyText: { fontSize: 14, color: '#6b7280', textAlign: 'center', lineHeight: 20 },
  createFirstButton: { backgroundColor: '#2563eb', paddingHorizontal: 24, paddingVertical: 12, borderRadius: 8, marginTop: 16 },
  createFirstButtonText: { color: '#ffffff', fontSize: 16, fontWeight: '600' },
  loadingContainer: { flex: 1, alignItems: 'center', justifyContent: 'center' },
  loadingText: { fontSize: 16, color: '#6b7280', marginTop: 12 },
  demoBanner: { backgroundColor: '#dbeafe', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6, marginBottom: 12, borderWidth: 1, borderColor: '#2563eb' },
  demoText: { fontSize: 12, color: '#1e40af', fontWeight: '600', textAlign: 'center' },
  demoSubtext: { fontSize: 10, color: '#1e40af', textAlign: 'center', marginTop: 2, opacity: 0.8 },
  errorContainer: { backgroundColor: '#fef2f2', borderRadius: 8, padding: 16, marginTop: 16, borderWidth: 1, borderColor: '#fecaca', alignItems: 'center' },
  errorText: { fontSize: 16, fontWeight: '600', color: '#dc2626', marginBottom: 8 },
  errorSubtext: { fontSize: 14, color: '#6b7280', textAlign: 'center', lineHeight: 20, marginBottom: 16 },
  retryButton: { backgroundColor: '#dc2626', paddingHorizontal: 20, paddingVertical: 10, borderRadius: 6 },
  retryButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
  statusInfo: { backgroundColor: '#fff3cd', borderRadius: 8, padding: 12, marginTop: 8, borderWidth: 1, borderColor: '#ffeaa7' },
  statusInfoText: { color: '#856404', fontSize: 14, fontWeight: '500', textAlign: 'center' },
  statusUpdateSection: { backgroundColor: '#f0f9ff', borderRadius: 8, padding: 12, marginTop: 12, borderWidth: 1, borderColor: '#bae6fd' },
  statusUpdateTitle: { fontSize: 14, fontWeight: '600', color: '#0369a1', marginBottom: 8 },
  statusUpdateButton: { backgroundColor: '#2563eb', paddingVertical: 10, paddingHorizontal: 16, borderRadius: 6, alignItems: 'center' },
  statusUpdateButtonText: { color: '#ffffff', fontSize: 14, fontWeight: '600' },
  progressSection: { backgroundColor: '#f8fafc', borderRadius: 8, padding: 12, marginTop: 12, borderWidth: 1, borderColor: '#e2e8f0' },
  progressTitle: { fontSize: 14, fontWeight: '600', color: '#334155', marginBottom: 12 },
  progressSteps: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  progressStep: { alignItems: 'center', flex: 1 },
  progressDot: { width: 24, height: 24, borderRadius: 12, backgroundColor: '#e2e8f0', alignItems: 'center', justifyContent: 'center', marginBottom: 4 },
  progressDotCompleted: { backgroundColor: '#059669' },
  progressDotCurrent: { backgroundColor: '#2563eb', borderWidth: 2, borderColor: '#ffffff', shadowColor: '#2563eb', shadowOffset: { width: 0, height: 0 }, shadowOpacity: 0.3, shadowRadius: 4, elevation: 4 },
  progressDotText: { color: '#ffffff', fontSize: 12, fontWeight: '600' },
  progressLabel: { fontSize: 10, color: '#64748b', textAlign: 'center', fontWeight: '500' },
  progressLabelCompleted: { color: '#059669', fontWeight: '600' },
  progressLabelCurrent: { color: '#2563eb', fontWeight: '600' },
  progressLine: { position: 'absolute', top: 12, left: '50%', right: '-50%', height: 2, backgroundColor: '#e2e8f0', zIndex: -1 },
  progressLineCompleted: { backgroundColor: '#059669' },
  
  // New streamlined styles
  fab: {
    position: 'absolute',
    bottom: 24,
    right: 24,
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#2563eb',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  
  cleanTabs: {
    flexDirection: 'row',
    backgroundColor: '#ffffff',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#e5e7eb',
  },
  
  cleanTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 8,
    borderRadius: 8,
    marginHorizontal: 4,
    gap: 6,
    position: 'relative',
  },
  
  cleanTabActive: {
    backgroundColor: '#eff6ff',
  },
  
  cleanTabText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
  },
  
  cleanTabTextActive: {
    color: '#2563eb',
  },
  
  tabBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: '#dc2626',
    borderRadius: 10,
    minWidth: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  
  tabBadgeText: {
    color: '#ffffff',
    fontSize: 10,
    fontWeight: '700',
  },
  
  simpleToggle: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderRadius: 8,
    padding: 2,
  },
  
  toggleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 6,
    gap: 4,
  },
  
  toggleActive: {
    backgroundColor: '#2563eb',
  },
  
  toggleText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6b7280',
  },
  
  toggleTextActive: {
    color: '#ffffff',
  },
  
  modernEmptyState: {
    alignItems: 'center',
    paddingVertical: 80,
    paddingHorizontal: 40,
  },
  
  emptyIconContainer: {
    width: 120,
    height: 120,
    borderRadius: 60,
    backgroundColor: '#f9fafb',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
    borderWidth: 2,
    borderColor: '#f3f4f6',
  },
  
  emptySubtitle: {
    fontSize: 14,
    color: '#9ca3af',
    textAlign: 'center',
    lineHeight: 20,
    marginTop: 8,
  },
});
