import { createElement } from 'react';
import { NextResponse } from 'next/server';
import { renderToBuffer } from '@react-pdf/renderer';
import { getAdminDb } from '@/lib/firebase-admin';
import { getAuthUserId, unauthorizedResponse } from '@/lib/api-auth';
import { getBookingById, serverTimestamp } from '@/lib/booking-store';
import { EmergencyPdfDocument } from '@/lib/emergency-pdf-document';
import { emergencyEmail, sendEmail } from '@/lib/email';
import type { User } from '@/types';

interface EmergencyPdfBody {
  bookingId: string;
}

export async function POST(request: Request): Promise<Response> {
  try {
    const userId = await getAuthUserId(request);
    if (!userId) return unauthorizedResponse();

    const body = (await request.json()) as EmergencyPdfBody;
    if (!body.bookingId) {
      return NextResponse.json({ error: 'bookingId is required' }, { status: 400 });
    }

    const booking = await getBookingById(body.bookingId);
    if (!booking) {
      return NextResponse.json({ error: 'Booking not found' }, { status: 404 });
    }

    if (booking.travellerId !== userId) {
      return NextResponse.json(
        { error: 'Only the traveller on this booking can generate an emergency document' },
        { status: 403 }
      );
    }

    const [travellerSnap, senderSnap] = await Promise.all([
      getAdminDb().collection('users').doc(booking.travellerId).get(),
      getAdminDb().collection('users').doc(booking.senderId).get(),
    ]);

    if (!travellerSnap.exists || !senderSnap.exists) {
      return NextResponse.json({ error: 'User records not found' }, { status: 404 });
    }

    const traveller = { uid: booking.travellerId, ...travellerSnap.data() } as User;
    const sender = { uid: booking.senderId, ...senderSnap.data() } as User;

    const generatedAt = new Date().toISOString();
    const appUrl = process.env.NEXT_PUBLIC_APP_URL ?? 'http://localhost:3000';
    const emergencyEmailAddress =
      process.env.EMERGENCY_EMAIL ?? 'emergency@carrymate.com.au';
    const emergencyPhone = process.env.EMERGENCY_PHONE ?? '+61200000000';

    const pdfBuffer = await renderToBuffer(
      createElement(EmergencyPdfDocument, {
        booking,
        traveller,
        sender,
        documentId: booking.id,
        generatedAt,
        appUrl,
        emergencyEmail: emergencyEmailAddress,
        emergencyPhone,
      }) as Parameters<typeof renderToBuffer>[0]
    );

    const incidentRef = getAdminDb().collection('incidents').doc();
    await incidentRef.set({
      id: incidentRef.id,
      bookingId: booking.id,
      userId,
      type: 'police_stop',
      description: 'Emergency police stop document generated by traveller',
      evidenceURLs: [],
      status: 'open',
      createdAt: serverTimestamp(),
      resolvedAt: null,
      adminNotes: '',
    });

    if (traveller.email) {
      await sendEmail({
        to: traveller.email,
        subject: 'Your CarryMate Emergency Document',
        html: `<p>Your emergency police stop document for booking ${booking.id} is attached.</p>`,
        attachments: [
          {
            filename: `carrymate-emergency-${booking.id}.pdf`,
            content: pdfBuffer,
          },
        ],
      });
    }

    const adminEmail = process.env.ADMIN_EMAIL;
    if (adminEmail) {
      const adminTemplate = emergencyEmail(booking.id);
      await sendEmail({
        to: adminEmail,
        ...adminTemplate,
        attachments: [
          {
            filename: `carrymate-emergency-${booking.id}.pdf`,
            content: pdfBuffer,
          },
        ],
      });
    }

    return new NextResponse(new Uint8Array(pdfBuffer), {
      status: 200,
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="carrymate-emergency-${booking.id}.pdf"`,
      },
    });
  } catch (error) {
    console.error('Emergency PDF error:', error);
    return NextResponse.json({ error: 'Failed to generate emergency PDF' }, { status: 500 });
  }
}
